### ISSUE TITLE
Vulnerability in @jc21/cypress-jwt-creation:0.0.4 version

### ISSUE THREAD

**Issue by gauravjeswani** [jc21/cypress-jwt-creation#15]
Vulnerability in @jc21/cypress-jwt-creation:0.0.4 version due to vulnerability in dependency  "jsonwebtoken": "^8.5.1". There is open MR for very long to fix it https://github.com/jc21/cypress-jwt-creation/pull/13.

**Comment by jc21** [comment]
Fixed in v0.0.5 onwards
